version: "2"
run:
  timeout: 5m
  go: ""
  build-tags: []
  allow-parallel-runners: false
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
linters:
  enable:
    - gochecknoinits
    - intrange
    - noctx
    - ineffassign
    - exhaustruct
    - gosmopolitan
    - unparam
    - unused
    - prealloc
    - wastedassign
    - reassign
    - recvcheck
    - bodyclose
    - forcetypeassert
    - nilerr
    - nilnesserr
    - paralleltest
    - unconvert
    - misspell
    - exhaustive
    - ginkgolinter
    - sqlclosecheck
    - dupl
    - goconst
    - protogetter
    - spancheck
    - govet
    - durationcheck
    - gochecknoglobals
    - mirror
    - thelper
    - staticcheck
    - errorlint
    - errcheck
    - revive
    - funlen
    - loggercheck
    - maintidx
    - errname
    - gosec
    - rowserrcheck
    - contextcheck
    - gocyclo
    - musttag
    - nakedret
    - predeclared
    - sloglint
    - usetesting
    - gocognit
    - nestif
    - wrapcheck
    - nolintlint
    - gocritic
    - testifylint
    - zerologlint
    - copyloopvar
    - cyclop
    - errchkjson
    - interfacebloat
    - perfsprint
    - gochecksumtype
    - nilnil
formatters:
  enable:
    - gofmt
    - goimports
    - golines
issues: {}
