// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
	"time"
)

type Users struct {
	ID              int64        `db:"id" json:"id"`
	UUID            string       `db:"uuid" json:"uuid"`
	Email           string       `db:"email" json:"email"`
	Username        string       `db:"username" json:"username"`
	PasswordHash    string       `db:"password_hash" json:"passwordHash"`
	FirstName       string       `db:"first_name" json:"firstName"`
	LastName        string       `db:"last_name" json:"lastName"`
	CreatedAt       time.Time    `db:"created_at" json:"createdAt"`
	UpdatedAt       time.Time    `db:"updated_at" json:"updatedAt"`
	LastLoginAt     interface{}  `db:"last_login_at" json:"lastLoginAt"`
	IsActive        sql.NullBool `db:"is_active" json:"isActive"`
	IsVerified      sql.NullBool `db:"is_verified" json:"isVerified"`
	ProfileMetadata interface{}  `db:"profile_metadata" json:"profileMetadata"`
}
