// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"context"
)

type Querier interface {
	//CountActiveUsers
	//
	//  SELECT COUNT(*) FROM users WHERE is_active = TRUE
	CountActiveUsers(ctx context.Context) (int64, error)
	//CreateUser
	//
	//  INSERT INTO users (
	//      uuid, email, username, password_hash,
	//      first_name, last_name, profile_metadata, is_active
	//  ) VALUES (
	//      ?, ?, ?, ?, ?, ?, ?, ?
	//  )
	//  RETURNING id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata
	CreateUser(ctx context.Context, arg *CreateUserParams) (*Users, error)
	//GetUserByEmail
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE email = ? AND is_active = TRUE
	GetUserByEmail(ctx context.Context, email string) (*Users, error)
	//GetUserByID
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE id = ? AND is_active = TRUE
	GetUserByID(ctx context.Context, id int64) (*Users, error)
	//GetUserByUUID
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE uuid = ? AND is_active = TRUE
	GetUserByUUID(ctx context.Context, uuid string) (*Users, error)
	//GetUserByUsername
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE username = ? AND is_active = TRUE
	GetUserByUsername(ctx context.Context, username string) (*Users, error)
	//GetUserStats
	//
	//  SELECT
	//      COUNT(*) as total_users,
	//      COUNT(CASE WHEN is_active = TRUE THEN 1 END) as active_users,
	//      COUNT(CASE WHEN is_verified = TRUE THEN 1 END) as verified_users,
	//      COUNT(CASE WHEN last_login_at IS NOT NULL THEN 1 END) as users_with_logins
	//  FROM users
	GetUserStats(ctx context.Context) (*GetUserStatsRow, error)
	//ListUsers
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users
	//  WHERE is_active = TRUE
	//  ORDER BY created_at DESC
	//  LIMIT ? OFFSET ?
	ListUsers(ctx context.Context, arg *ListUsersParams) ([]*Users, error)
	//SoftDeleteUser
	//
	//  UPDATE users
	//  SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
	//  WHERE id = ?
	SoftDeleteUser(ctx context.Context, id int64) error
	//UpdateLastLogin
	//
	//  UPDATE users
	//  SET last_login_at = CURRENT_TIMESTAMP
	//  WHERE id = ?
	UpdateLastLogin(ctx context.Context, id int64) error
	//UpdatePassword
	//
	//  UPDATE users
	//  SET password_hash = ?, updated_at = CURRENT_TIMESTAMP
	//  WHERE id = ?
	UpdatePassword(ctx context.Context, arg *UpdatePasswordParams) error
	//UpdateUser
	//
	//  UPDATE users
	//  SET
	//      email = COALESCE(?, email),
	//      username = COALESCE(?, username),
	//      first_name = COALESCE(?, first_name),
	//      last_name = COALESCE(?, last_name),
	//      profile_metadata = COALESCE(?, profile_metadata),
	//      is_active = COALESCE(?, is_active),
	//      is_verified = COALESCE(?, is_verified)
	//  WHERE id = ?
	//  RETURNING id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*Users, error)
	//VerifyUser
	//
	//  UPDATE users
	//  SET is_verified = TRUE, updated_at = CURRENT_TIMESTAMP
	//  WHERE uuid = ?
	VerifyUser(ctx context.Context, uuid string) error
}

var _ Querier = (*Queries)(nil)
