//go:build mysql

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//
// This file uses the shared package for common types to avoid code duplication.

package mysql

import (
	"github.com/LarsArtmann/template-sqlc/internal/db/shared"
)

// DBTX is imported from shared package
type DBTX = shared.DBTX

// Queries struct - embeds shared.BaseQueries and has db field for DBTX access
type Queries struct {
	*shared.BaseQueries
	db DBTX
}

// New returns a new Queries instance
func New(db DBTX) *Queries {
	return &Queries{
		db:          db,
		BaseQueries: shared.NewBase(db),
	}
}
