//go:build mysql

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mysql

import (
	"database/sql"

	"github.com/LarsArtmann/template-sqlc/internal/db/shared"
)

// DBTX is an alias to the shared DBTX interface
type DBTX = shared.DBTX

func New(db DBTX) *Queries {
	return &Queries{DB: db}
}

type Queries struct {
	DB DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		DB: tx,
	}
}
