//go:build mysql

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//
// This file uses type aliases to the shared package to avoid code duplication.

package mysql

import (
	"github.com/LarsArtmann/template-sqlc/internal/db/shared"
)

type DBTX = shared.DBTX

type Queries = shared.Queries

func New(db DBTX) *Queries {
	return shared.New(db)
}
