//go:build mysql

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package mysql

import (
	"context"
	"database/sql"
	"encoding/json"

	"json"
)

const CountActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE is_active = TRUE
`

// CountActiveUsers
//
//	SELECT COUNT(*) FROM users WHERE is_active = TRUE
func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countActiveUsersStmt, CountActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateUser = `-- name: CreateUser :execresult
INSERT INTO users (
    uuid, email, username, password_hash, 
    first_name, last_name, profile_metadata, is_active
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	UUID            string          `db:"uuid" json:"uuid"`
	Email           string          `db:"email" json:"email"`
	Username        string          `db:"username" json:"username"`
	PasswordHash    string          `db:"password_hash" json:"passwordHash"`
	FirstName       string          `db:"first_name" json:"firstName"`
	LastName        string          `db:"last_name" json:"lastName"`
	ProfileMetadata json.RawMessage `db:"profile_metadata" json:"profileMetadata"`
	IsActive        sql.NullBool    `db:"is_active" json:"isActive"`
}

// CreateUser
//
//	INSERT INTO users (
//	    uuid, email, username, password_hash,
//	    first_name, last_name, profile_metadata, is_active
//	) VALUES (
//	    ?, ?, ?, ?, ?, ?, ?, ?
//	)
func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (sql.Result, error) {
	return q.exec(ctx, q.createUserStmt, CreateUser,
		arg.UUID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.ProfileMetadata,
		arg.IsActive,
	)
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE email = ? AND is_active = TRUE
`

// GetUserByEmail
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE email = ? AND is_active = TRUE
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*Users, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, GetUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE id = ? AND is_active = TRUE
`

// GetUserByID
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE id = ? AND is_active = TRUE
func (q *Queries) GetUserByID(ctx context.Context, id uint64) (*Users, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, GetUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const GetUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE uuid = ? AND is_active = TRUE
`

// GetUserByUUID
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE uuid = ? AND is_active = TRUE
func (q *Queries) GetUserByUUID(ctx context.Context, uuid string) (*Users, error) {
	row := q.queryRow(ctx, q.getUserByUUIDStmt, GetUserByUUID, uuid)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const GetUserByUsername = `-- name: GetUserByUsername :one
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE username = ? AND is_active = TRUE
`

// GetUserByUsername
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE username = ? AND is_active = TRUE
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*Users, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, GetUserByUsername, username)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const GetUserStats = `-- name: GetUserStats :one
SELECT 
    COUNT(*) as total_users,
    SUM(CASE WHEN is_active = TRUE THEN 1 ELSE 0 END) as active_users,
    SUM(CASE WHEN is_verified = TRUE THEN 1 ELSE 0 END) as verified_users,
    SUM(CASE WHEN last_login_at IS NOT NULL THEN 1 ELSE 0 END) as users_with_logins
FROM users
`

type GetUserStatsRow struct {
	TotalUsers      int64       `db:"total_users" json:"totalUsers"`
	ActiveUsers     interface{} `db:"active_users" json:"activeUsers"`
	VerifiedUsers   interface{} `db:"verified_users" json:"verifiedUsers"`
	UsersWithLogins interface{} `db:"users_with_logins" json:"usersWithLogins"`
}

// GetUserStats
//
//	SELECT
//	    COUNT(*) as total_users,
//	    SUM(CASE WHEN is_active = TRUE THEN 1 ELSE 0 END) as active_users,
//	    SUM(CASE WHEN is_verified = TRUE THEN 1 ELSE 0 END) as verified_users,
//	    SUM(CASE WHEN last_login_at IS NOT NULL THEN 1 ELSE 0 END) as users_with_logins
//	FROM users
func (q *Queries) GetUserStats(ctx context.Context) (*GetUserStatsRow, error) {
	row := q.queryRow(ctx, q.getUserStatsStmt, GetUserStats)
	var i GetUserStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.VerifiedUsers,
		&i.UsersWithLogins,
	)
	return &i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users 
WHERE is_active = TRUE 
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// ListUsers
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users
//	WHERE is_active = TRUE
//	ORDER BY created_at DESC
//	LIMIT ? OFFSET ?
func (q *Queries) ListUsers(ctx context.Context, arg *ListUsersParams) ([]*Users, error) {
	rows, err := q.query(ctx, q.listUsersStmt, ListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.IsActive,
			&i.IsVerified,
			&i.ProfileMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users 
SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

// SoftDeleteUser
//
//	UPDATE users
//	SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
//	WHERE id = ?
func (q *Queries) SoftDeleteUser(ctx context.Context, id uint64) error {
	_, err := q.exec(ctx, q.softDeleteUserStmt, SoftDeleteUser, id)
	return err
}

const UpdateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users 
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = ?
`

// UpdateLastLogin
//
//	UPDATE users
//	SET last_login_at = CURRENT_TIMESTAMP
//	WHERE id = ?
func (q *Queries) UpdateLastLogin(ctx context.Context, id uint64) error {
	_, err := q.exec(ctx, q.updateLastLoginStmt, UpdateLastLogin, id)
	return err
}

const UpdatePassword = `-- name: UpdatePassword :exec
UPDATE users 
SET password_hash = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePasswordParams struct {
	PasswordHash string `db:"password_hash" json:"passwordHash"`
	ID           uint64 `db:"id" json:"id"`
}

// UpdatePassword
//
//	UPDATE users
//	SET password_hash = ?, updated_at = CURRENT_TIMESTAMP
//	WHERE id = ?
func (q *Queries) UpdatePassword(ctx context.Context, arg *UpdatePasswordParams) error {
	_, err := q.exec(ctx, q.updatePasswordStmt, UpdatePassword, arg.PasswordHash, arg.ID)
	return err
}

const UpdateUser = `-- name: UpdateUser :execresult
UPDATE users 
SET 
    email = COALESCE(?, email),
    username = COALESCE(?, username),
    first_name = COALESCE(?, first_name),
    last_name = COALESCE(?, last_name),
    profile_metadata = COALESCE(?, profile_metadata),
    is_active = COALESCE(?, is_active),
    is_verified = COALESCE(?, is_verified)
WHERE id = ?
`

type UpdateUserParams struct {
	Email           string          `db:"email" json:"email"`
	Username        string          `db:"username" json:"username"`
	FirstName       string          `db:"first_name" json:"firstName"`
	LastName        string          `db:"last_name" json:"lastName"`
	ProfileMetadata json.RawMessage `db:"profile_metadata" json:"profileMetadata"`
	IsActive        sql.NullBool    `db:"is_active" json:"isActive"`
	IsVerified      sql.NullBool    `db:"is_verified" json:"isVerified"`
	ID              uint64          `db:"id" json:"id"`
}

// UpdateUser
//
//	UPDATE users
//	SET
//	    email = COALESCE(?, email),
//	    username = COALESCE(?, username),
//	    first_name = COALESCE(?, first_name),
//	    last_name = COALESCE(?, last_name),
//	    profile_metadata = COALESCE(?, profile_metadata),
//	    is_active = COALESCE(?, is_active),
//	    is_verified = COALESCE(?, is_verified)
//	WHERE id = ?
func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) (sql.Result, error) {
	return q.exec(ctx, q.updateUserStmt, UpdateUser,
		arg.Email,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.ProfileMetadata,
		arg.IsActive,
		arg.IsVerified,
		arg.ID,
	)
}

const VerifyUser = `-- name: VerifyUser :exec
UPDATE users 
SET is_verified = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE uuid = ?
`

// VerifyUser
//
//	UPDATE users
//	SET is_verified = TRUE, updated_at = CURRENT_TIMESTAMP
//	WHERE uuid = ?
func (q *Queries) VerifyUser(ctx context.Context, uuid string) error {
	_, err := q.exec(ctx, q.verifyUserStmt, VerifyUser, uuid)
	return err
}
