//go:build postgres

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Users struct {
	ID              int64              `db:"id" json:"id"`
	UUID            uuid.UUID          `db:"uuid" json:"uuid"`
	Email           string             `db:"email" json:"email"`
	Username        string             `db:"username" json:"username"`
	PasswordHash    string             `db:"password_hash" json:"passwordHash"`
	FirstName       string             `db:"first_name" json:"firstName"`
	LastName        string             `db:"last_name" json:"lastName"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	LastLoginAt     pgtype.Timestamptz `db:"last_login_at" json:"lastLoginAt"`
	IsActive        *bool              `db:"is_active" json:"isActive"`
	IsVerified      *bool              `db:"is_verified" json:"isVerified"`
	ProfileMetadata []byte             `db:"profile_metadata" json:"profileMetadata"`
}
