//go:build postgres

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	//CountActiveUsers
	//
	//  SELECT COUNT(*) FROM users WHERE is_active = TRUE
	CountActiveUsers(ctx context.Context) (int64, error)
	//CreateUser
	//
	//  INSERT INTO users (
	//      uuid, email, username, password_hash,
	//      first_name, last_name, profile_metadata, is_active
	//  ) VALUES (
	//      $1, $2, $3, $4, $5, $6, $7, $8
	//  )
	//  RETURNING id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata
	CreateUser(ctx context.Context, arg *CreateUserParams) (*Users, error)
	//GetUserByEmail
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE email = $1 AND is_active = TRUE
	GetUserByEmail(ctx context.Context, email string) (*Users, error)
	//GetUserByID
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE id = $1 AND is_active = TRUE
	GetUserByID(ctx context.Context, id int64) (*Users, error)
	//GetUserByUUID
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE uuid = $1 AND is_active = TRUE
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (*Users, error)
	//GetUserByUsername
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE username = $1 AND is_active = TRUE
	GetUserByUsername(ctx context.Context, username string) (*Users, error)
	//GetUserStats
	//
	//  SELECT
	//      COUNT(*) as total_users,
	//      COUNT(*) FILTER (WHERE is_active = TRUE) as active_users,
	//      COUNT(*) FILTER (WHERE is_verified = TRUE) as verified_users,
	//      COUNT(*) FILTER (WHERE last_login_at IS NOT NULL) as users_with_logins
	//  FROM users
	GetUserStats(ctx context.Context) (*GetUserStatsRow, error)
	//ListUsers
	//
	//  SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users
	//  WHERE is_active = TRUE
	//  ORDER BY created_at DESC
	//  LIMIT $1 OFFSET $2
	ListUsers(ctx context.Context, arg *ListUsersParams) ([]*Users, error)
	//SoftDeleteUser
	//
	//  UPDATE users
	//  SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
	//  WHERE id = $1
	SoftDeleteUser(ctx context.Context, id int64) error
	//UpdateLastLogin
	//
	//  UPDATE users
	//  SET last_login_at = CURRENT_TIMESTAMP
	//  WHERE id = $1
	UpdateLastLogin(ctx context.Context, id int64) error
	//UpdatePassword
	//
	//  UPDATE users
	//  SET password_hash = $2, updated_at = CURRENT_TIMESTAMP
	//  WHERE id = $1
	UpdatePassword(ctx context.Context, arg *UpdatePasswordParams) error
	//UpdateUser
	//
	//  UPDATE users
	//  SET
	//      email = COALESCE($2, email),
	//      username = COALESCE($3, username),
	//      first_name = COALESCE($4, first_name),
	//      last_name = COALESCE($5, last_name),
	//      profile_metadata = COALESCE($6, profile_metadata),
	//      is_active = COALESCE($7, is_active),
	//      is_verified = COALESCE($8, is_verified)
	//  WHERE id = $1
	//  RETURNING id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*Users, error)
	//VerifyUser
	//
	//  UPDATE users
	//  SET is_verified = TRUE, updated_at = CURRENT_TIMESTAMP
	//  WHERE uuid = $1
	VerifyUser(ctx context.Context, argUuid uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
