//go:build postgres

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const CountActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE is_active = TRUE
`

// CountActiveUsers
//
//	SELECT COUNT(*) FROM users WHERE is_active = TRUE
func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (
    uuid, email, username, password_hash, 
    first_name, last_name, profile_metadata, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata
`

type CreateUserParams struct {
	UUID            uuid.UUID `db:"uuid" json:"uuid"`
	Email           string    `db:"email" json:"email"`
	Username        string    `db:"username" json:"username"`
	PasswordHash    string    `db:"password_hash" json:"passwordHash"`
	FirstName       string    `db:"first_name" json:"firstName"`
	LastName        string    `db:"last_name" json:"lastName"`
	ProfileMetadata []byte    `db:"profile_metadata" json:"profileMetadata"`
	IsActive        *bool     `db:"is_active" json:"isActive"`
}

// CreateUser
//
//	INSERT INTO users (
//	    uuid, email, username, password_hash,
//	    first_name, last_name, profile_metadata, is_active
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6, $7, $8
//	)
//	RETURNING id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata
func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*Users, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.UUID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.ProfileMetadata,
		arg.IsActive,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE email = $1 AND is_active = TRUE
`

// GetUserByEmail
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE email = $1 AND is_active = TRUE
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*Users, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE id = $1 AND is_active = TRUE
`

// GetUserByID
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE id = $1 AND is_active = TRUE
func (q *Queries) GetUserByID(ctx context.Context, id int64) (*Users, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const GetUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE uuid = $1 AND is_active = TRUE
`

// GetUserByUUID
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE uuid = $1 AND is_active = TRUE
func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (*Users, error) {
	row := q.db.QueryRow(ctx, GetUserByUUID, argUuid)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const GetUserByUsername = `-- name: GetUserByUsername :one
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE username = $1 AND is_active = TRUE
`

// GetUserByUsername
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users WHERE username = $1 AND is_active = TRUE
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*Users, error) {
	row := q.db.QueryRow(ctx, GetUserByUsername, username)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const GetUserStats = `-- name: GetUserStats :one
SELECT 
    COUNT(*) as total_users,
    COUNT(*) FILTER (WHERE is_active = TRUE) as active_users,
    COUNT(*) FILTER (WHERE is_verified = TRUE) as verified_users,
    COUNT(*) FILTER (WHERE last_login_at IS NOT NULL) as users_with_logins
FROM users
`

type GetUserStatsRow struct {
	TotalUsers      int64 `db:"total_users" json:"totalUsers"`
	ActiveUsers     int64 `db:"active_users" json:"activeUsers"`
	VerifiedUsers   int64 `db:"verified_users" json:"verifiedUsers"`
	UsersWithLogins int64 `db:"users_with_logins" json:"usersWithLogins"`
}

// GetUserStats
//
//	SELECT
//	    COUNT(*) as total_users,
//	    COUNT(*) FILTER (WHERE is_active = TRUE) as active_users,
//	    COUNT(*) FILTER (WHERE is_verified = TRUE) as verified_users,
//	    COUNT(*) FILTER (WHERE last_login_at IS NOT NULL) as users_with_logins
//	FROM users
func (q *Queries) GetUserStats(ctx context.Context) (*GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, GetUserStats)
	var i GetUserStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.VerifiedUsers,
		&i.UsersWithLogins,
	)
	return &i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users 
WHERE is_active = TRUE 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// ListUsers
//
//	SELECT id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata FROM users
//	WHERE is_active = TRUE
//	ORDER BY created_at DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListUsers(ctx context.Context, arg *ListUsersParams) ([]*Users, error) {
	rows, err := q.db.Query(ctx, ListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.IsActive,
			&i.IsVerified,
			&i.ProfileMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users 
SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// SoftDeleteUser
//
//	UPDATE users
//	SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, SoftDeleteUser, id)
	return err
}

const UpdateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users 
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// UpdateLastLogin
//
//	UPDATE users
//	SET last_login_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) UpdateLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, UpdateLastLogin, id)
	return err
}

const UpdatePassword = `-- name: UpdatePassword :exec
UPDATE users 
SET password_hash = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int64  `db:"id" json:"id"`
	PasswordHash string `db:"password_hash" json:"passwordHash"`
}

// UpdatePassword
//
//	UPDATE users
//	SET password_hash = $2, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) UpdatePassword(ctx context.Context, arg *UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, UpdatePassword, arg.ID, arg.PasswordHash)
	return err
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE users 
SET 
    email = COALESCE($2, email),
    username = COALESCE($3, username),
    first_name = COALESCE($4, first_name),
    last_name = COALESCE($5, last_name),
    profile_metadata = COALESCE($6, profile_metadata),
    is_active = COALESCE($7, is_active),
    is_verified = COALESCE($8, is_verified)
WHERE id = $1
RETURNING id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata
`

type UpdateUserParams struct {
	ID              int64  `db:"id" json:"id"`
	Email           string `db:"email" json:"email"`
	Username        string `db:"username" json:"username"`
	FirstName       string `db:"first_name" json:"firstName"`
	LastName        string `db:"last_name" json:"lastName"`
	ProfileMetadata []byte `db:"profile_metadata" json:"profileMetadata"`
	IsActive        *bool  `db:"is_active" json:"isActive"`
	IsVerified      *bool  `db:"is_verified" json:"isVerified"`
}

// UpdateUser
//
//	UPDATE users
//	SET
//	    email = COALESCE($2, email),
//	    username = COALESCE($3, username),
//	    first_name = COALESCE($4, first_name),
//	    last_name = COALESCE($5, last_name),
//	    profile_metadata = COALESCE($6, profile_metadata),
//	    is_active = COALESCE($7, is_active),
//	    is_verified = COALESCE($8, is_verified)
//	WHERE id = $1
//	RETURNING id, uuid, email, username, password_hash, first_name, last_name, created_at, updated_at, last_login_at, is_active, is_verified, profile_metadata
func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) (*Users, error) {
	row := q.db.QueryRow(ctx, UpdateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.ProfileMetadata,
		arg.IsActive,
		arg.IsVerified,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsActive,
		&i.IsVerified,
		&i.ProfileMetadata,
	)
	return &i, err
}

const VerifyUser = `-- name: VerifyUser :exec
UPDATE users 
SET is_verified = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE uuid = $1
`

// VerifyUser
//
//	UPDATE users
//	SET is_verified = TRUE, updated_at = CURRENT_TIMESTAMP
//	WHERE uuid = $1
func (q *Queries) VerifyUser(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, VerifyUser, argUuid)
	return err
}
