#!/bin/bash
set -e

# Run sqlc generate
sqlc generate

# Deduplicate db.go files between MySQL and SQLite
# Both use database/sql and generate identical DBTX interface + Queries struct.
# This script post-processes both to use a shared package for common types.

SQLITE_DB="internal/db/sqlite/db.go"
MYSQL_DB="internal/db/mysql/db.go"

# Generate the shared-based db.go content for both SQLite and MySQL
generate_db_go() {
    local pkg="$1"
    local build_tag="$2"

    if [ -n "$build_tag" ]; then
        echo "//go:build $build_tag"
        echo ""
    fi

    cat << 'INNEREOF'
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//
// This file uses the shared package for common types to avoid code duplication.

package INNEREOF
    echo "$pkg"
    echo ""
    cat << 'INNEREOF2'
import (
	"github.com/LarsArtmann/template-sqlc/internal/db/shared"
)

// DBTX is imported from shared package
type DBTX = shared.DBTX

// Queries struct - embeds shared.BaseQueries and has db field for DBTX access
type Queries struct {
	*shared.BaseQueries
	db DBTX
}

// New returns a new Queries instance
func New(db DBTX) *Queries {
	return &Queries{
		db:          db,
		BaseQueries: shared.NewBase(db),
	}
}
INNEREOF2
}

# Replace sqlite/db.go
generate_db_go "sqlite" "" > "$SQLITE_DB"

# Replace mysql/db.go
generate_db_go "mysql" "mysql" > "$MYSQL_DB"

# Fix MySQL duplicate json imports (sqlc bug)
# The generated code imports both "encoding/json" and "json"
for file in internal/db/mysql/models.go internal/db/mysql/user.sql.go; do
	if [ -f "$file" ]; then
		grep -v '^\s*"json"$' "$file" > "$file.tmp" || true
		mv "$file.tmp" "$file"
	fi
done

echo "Code generation and deduplication complete"
