#!/bin/bash
set -e

# Run sqlc generate
sqlc generate

# Deduplicate db.go files between MySQL and SQLite
# Both use database/sql and generate identical DBTX interface + Queries struct.
# Post-process to use type aliases to shared package.

SQLITE_DB="internal/db/sqlite/db.go"
MYSQL_DB="internal/db/mysql/db.go"

# Generate the shared-based db.go content for both SQLite and MySQL
generate_db_go() {
    local pkg="$1"
    local build_tag="$2"

    if [ -n "$build_tag" ]; then
        echo "//go:build $build_tag"
        echo ""
    fi

    cat << EOF
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//
// This file uses type aliases to the shared package to avoid code duplication.

package $pkg

import (
	"github.com/LarsArtmann/template-sqlc/internal/db/shared"
)

type DBTX = shared.DBTX

type Queries = shared.Queries

func New(db DBTX) *Queries {
	return shared.New(db)
}
EOF
}

# Replace sqlite/db.go with sqlite build tag
generate_db_go "sqlite" "sqlite" > "$SQLITE_DB"

# Replace mysql/db.go
generate_db_go "mysql" "mysql" > "$MYSQL_DB"

# Fix MySQL duplicate json imports (sqlc bug)
for file in internal/db/mysql/models.go internal/db/mysql/user.sql.go; do
	if [ -f "$file" ]; then
		grep -v '^\s*"json"$' "$file" > "$file.tmp" || true
		mv "$file.tmp" "$file"
	fi
done

echo "Code generation and deduplication complete"
