#!/bin/bash
set -e

# Run sqlc generate
sqlc generate

# Deduplicate db.go files between MySQL and SQLite
# Both use database/sql and generate identical code.
# This script post-processes to use a shared package for common types.

SQLITE_DB="internal/db/sqlite/db.go"

# Replace sqlite/db.go to use shared package for common types
cat > "$SQLITE_DB" << 'EOFILE'
//go:build sqlite

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//
// This file uses the shared package for common types to avoid code duplication.

package sqlite

import (
	"github.com/LarsArtmann/template-sqlc/internal/db/shared"
)

// DBTX is imported from shared package
type DBTX = shared.DBTX

// Queries struct - embeds shared.BaseQueries and has db field for DBTX access
type Queries struct {
	*shared.BaseQueries
	db DBTX
}

// New returns a new Queries instance
func New(db DBTX) *Queries {
	return &Queries{
		db:           db,
		BaseQueries:  shared.NewBase(db),
	}
}
EOFILE

# Fix MySQL duplicate json imports (sqlc bug)
# The generated code imports both "encoding/json" and "json"
for file in internal/db/mysql/models.go internal/db/mysql/user.sql.go; do
	if [ -f "$file" ]; then
		# Remove lines containing just "json" import
		grep -v '^\s*"json"$' "$file" > "$file.tmp" || true
		mv "$file.tmp" "$file"
	fi
done

echo "Code generation and deduplication complete"
